# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag_id',
            field=models.IntegerField(default=0, verbose_name='tag id'),
        ),
    ]
